version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_recepcion
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Dbs.2023..,
      MYSQL_DATABASE: recepcion_dbs
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 5s
  api:
    build: .
    container_name: api_recepcion
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"   # accedes por http://localhost:8000
    volumes:
      - .:/app # Monta el directorio actual en /app dentro del contenedor
volumes:
  mysql_data: