version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_recepcion
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
  api:
    build: .
    container_name: api_recepcion
    restart: always
    depends_on:
      - mysql
    ports:
      - "8000:8000"   # accedes por http://localhost:8000
    volumes:
      - .:/app # Monta el directorio actual en /app dentro del contenedor
volumes:
  mysql_data: